#!/usr/bin/env python3
from benchmarks.utils import Runner
import click


@click.command()
@click.argument("config_file", type=click.Path(exists=True))
def cli(config_file):
    runner = Runner(config_file)
    runner.run()


if __name__ == "__main__":
    cli()
